### ISSUE TITLE
Button don't change state according to simulated state

### ISSUE THREAD

**Issue by jamesperez2005** [wortelus/xplane-streamdeck#8]
I followed the instructions to set up xplane-streamdeck and I got it to work. When I press Master Caution, FMC Reset etc. they trigger the correct action in the sim. Also, the flaps state dial updates based on the correct state in the sim as well.

However, I noticed that the annunciator buttons (master caution, flap transit, speedbrake arm etc.) don't get highlighted when their respective state in the sim changes. I tried several times, including triggering fire tests and the highlighting doesn't seem to work.

I'm using latest Xplane 12, and Zibo 737-800X

**Comment by wortelus** [comment]
Hello,
there is a fair possibility that dataref names could have changed with latest versions of Zibo. Also in past X-Plane contained a bug (in its UDP protocol handling) where the restart of `xplane-streamdeck` was necessary, after that it worked like before and was pretty rare to occur.

I will take a look at this when I see to it in the following days.

Thanks for the report :)

wortelus

**Comment by jamesperez2005** [comment]
@wortelus That would be greatly appreciated! xplane-streamdeck is awesome and it really adds a lot to the X-plane experience! Thank you very much for this tool!

**Comment by wortelus** [comment]
I am in the process of fixing this issue and I have identified the problem.

The problem lies in the way how the dataref values look like for lighten up annunciators, the value for annunciator in ON state has been in the past around ~0.7. Now it floats around ~0.5. This value changes with time as you start up the cockpit, and I am yet to understand why that happens.

My unconfirmed theory is that Zibo likes to play with the light bulb shininess according to some external conditions :)

Nudging the dataref multiplier was the way of solving this until now, but that seems like a half baked solution now.

Expect working solution in the following day or two.

wortelus

**Comment by wortelus** [comment]
Once again, thank you for your report, @jamesperez2005.
It means a lot to me to see the community still actively engage and benefit from this plugin. 😊 

The fix has now been deployed in version **1.4.1**. I have conducted some tests on the most recent versions of Zibo (_4.01.3_) and X-Plane (_12.09_), ensuring everything operates smoothly. Additionally, I've implemented some corrections, particularly concerning some classic and blue 3-state annunciators.

With all necessary adjustments in place, I am proceeding to close this issue, marking it as resolved. Should you encounter any further difficulties, or if you have additional questions or comments, please do not hesitate to reopen this issue.

EDIT: the values have been nudged further in #10

Warm regards,

wortelus

**Comment by jamesperez2005** [comment]
Thank you very very much for your effort and hard work! Much appreciated! I can confirm the fix works!
